### ISSUE TITLE
Design and flow

### ISSUE THREAD

**Issue by jasonmccallister** [realtimdunbar/zen_console#1]
@realtimdunbar I think we should use this ticket to track our thoughts on how to perform a basic flow. The first step in my mind is to "design" the flow for each request type (REST to be specific)

I'm going to jot my initial ideas for an index request (leaving out search params)

1. HTTP GET on `/resource`
2. The package would parse the path to the main file or directory (e.g. `resource`) and find the YAML file
3. Load the YAML and convert to JSON 
4. Return

First question is how would the folder be organized, is it one YAML with all of the data or the directory with individual YAML files?

**Comment by realtimdunbar** [comment]
I'd say unless there is a performance issue it should all be one highly nested file.  I'm going with the philosophy that the yaml file itself does not need to be easily human readable, therefore it is not necessary that we organise it for humans.  Thoughts?

**Comment by realtimdunbar** [comment]
Actually we should split it up, if the file is huge it won't be able to load into memory.  Perhaps make that a user choice, which field to split on.
